# Generated by Django 3.0.7 on 2021-02-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_url', models.CharField(max_length=256)),
                ('filepath', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('thread_index', models.IntegerField()),
            ],
        ),
    ]
