# Generated by Django 3.0.7 on 2021-02-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='filepath',
            new_name='filename',
        ),
    ]
