# Generated by Django 3.0.7 on 2021-02-07 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20210207_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
