# Generated by Django 3.0.7 on 2021-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_auto_20210207_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorder',
            name='filename',
        ),
        migrations.AddField(
            model_name='recorder',
            name='foldername',
            field=models.CharField(default='tmp', max_length=64),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='stream_url',
            field=models.CharField(default='demo.mp4', max_length=256),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='thread_index',
            field=models.IntegerField(default=0),
        ),
    ]
