# Generated by Django 3.0.7 on 2021-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_auto_20210207_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='thread_index',
            new_name='task_id',
        ),
    ]
