# Generated by Django 3.0.7 on 2021-02-08 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_auto_20210208_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorder',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
