# Generated by Django 3.0.7 on 2021-02-08 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0006_auto_20210208_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
