# Generated by Django 3.0.7 on 2021-02-09 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0007_recorder_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='foldername',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='recorder',
            old_name='stream_url',
            new_name='url',
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.Recorder')),
            ],
        ),
    ]
