# Generated by Django 3.0.7 on 2021-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0008_auto_20210209_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
