# Generated by Django 3.0.7 on 2021-02-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0010_recording_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='active',
        ),
    ]
