# Generated by Django 3.0.7 on 2021-02-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0011_remove_recording_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='schedule_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recorder',
            name='schedule_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
